spring:
  config:
    activate:
      on-profile: development
logging:
  level:
    com:
      kuretru:
        web:
          gemini:
            mapper: debug
galaxy:
  oauth2:
    server:
      front-end-url: http://127.0.0.1:7052
