---
- hosts: gemini
  gather_facts: false
  remote_user: root
  vars:
    root_path: /home/nginx/oauth2.i5zhen.com
  tasks:
  - name: extract content
    unarchive: 
      src: ../../Gemini-OAuth2-Web/dist.tar.gz
      dest: "{{ root_path }}"
  - name: remove old content
    file: 
      path: "{{ root_path }}/public_bk"
      state: absent
  - name: backup old content
    shell: 
      chdir: "{{ root_path }}"
      cmd: mv public/ public_bk/
  - name: apply new content
    shell: 
      chdir: "{{ root_path }}"
      cmd: mv dist/ public/
  - name: change owner and mode
    file: 
      path: "{{ root_path }}/public"
      owner: nginx
      group: nginx
      mode: 0755
      recurse: yes
