name: CI
on: [ push, pull_request ]
jobs:
  build-backend:
    name: build backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build Gemini OAuth Parent
        run: mvn --batch-mode --update-snapshots install
        working-directory: Gemini-OAuth2-Api/
